data:
    #lif_path: "/home/sasce/PycharmProjects/cellseg3d/data/2025.07.24_right_after_seeding.lif"
    lif_path: "/home/sasce/PycharmProjects/cellseg3d/data/Project.lif"
    valid_idx: [5]
    output_dir: "/home/sasce/PycharmProjects/cellseg3d/data/out/"

acquisition:
    default_spacing_um:
        dz: 1.0
        dy: 1.0
        dx: 1.0

segmentation:
    denoise_method: "none" # "tv" | "nlm" | "bilateral" | "gaussian" | "wavelet" | "none"
    denoise_params:
        patch_size: 3 # example for NLM
        patch_distance: 5
        sigma_color: 0.1 # example for bilateral
        target_um: 0.6 # example for Gaussian

    # -------- threshold (for the cell channel) --------
    threshold:
        method: "otsu" # 'otsu'|'yen'|'li'|'triangle'|'percentile'
        percentile: 99.2 # only used if method == 'percentile'

    # -------- morphology (pre-watershed) --------
    min_voxels: 200 # remove objects smaller than this (voxels)
    morphology:
        open_radius: 1
        close_radius: 0

    # -------- tissue prior (channel-1) to steer watershed --------
    tissue_prior:
        enabled: true
        mode: "normalize" # 'normalize' | 'threshold'
        weight: 0.8 # higher => stronger ridge along tissue
        norm_clip: [1.0, 99.0] # only used in 'normalize' mode
        threshold_method: "yen" # used in 'threshold' mode
        threshold_percentile: 95.0 # used in 'threshold' mode

    # -------- watershed (splitting) --------
    watershed:
        enabled: true
        method: "hmax" # 'hmax' | 'peaks'
        h: 0.75
        footprint: 3
        compactness: 0.5

    # -------- extra cleanup after binarization --------
    post_open_radius: 1
    post_close_radius: 0

visualization:
    enabled: true
    show_labels: true
    points_size: 10
    render_3d: false
    volume_mode: "translucent" # translucent|mip|attenuated_mip|additive
    surface:
        make: false
        smoothing: 1.0
        level: 0.5
        downsample: 1

runtime:
    log_level: "INFO"
