lif_path: "/home/sasce/PycharmProjects/cellseg3d/data/Project.lif"
valid_idx: [2, 4, 5]
#lif_path: "/home/sasce/PycharmProjects/cellseg3d/data/2025.07.24_right_after_seeding.lif"
#valid_idx: [8]
#lif_path: "/home/sasce/PycharmProjects/cellseg3d/data/2025.07.08_nuclei-actin.lif"
#valid_idx: [2]

# segmentation
preferred_channel: 0
preferred_timepoint: 0
min_voxels: 100 # remove objects smaller than this (in voxels)

# --- segmentation ---
open_radius: 1 # binary opening radius in voxels
close_radius: 0 # binary closing radius in voxels

# --- watershed split (touching cells) ---
watershed_enabled: true
watershed_method: "hmax" # "hmax" or "peaks"
watershed_h: 0.75 # h for h-maxima on the distance map (voxels)
watershed_footprint: 3 # local neighborhood (cube size) for peaks
watershed_compactness: 0.5 # 0 = standard watershed; >0 = more rounded cells, 1 = perfect spheres

# voxel spacing fallback (µm) if metadata is missing
default_spacing_um:
    dz: 1.0
    dy: 1.0
    dx: 1.0

# outputs
output_dir: /home/sasce/PycharmProjects/cellseg3d/data/out/ # null -> "<lif_basename>/" next to the .lif; or set a custom folder

# visualization
visualize: true
show_labels: true
points_size: 5

# 3D rendering
render_3d: false # <-- enable real 3D view (no z slider)
volume_mode: "translucent" # one of: "translucent", "mip", "attenuated_mip", "additive"
make_surface: false # extract a 3D surface mesh from labels
surface_smoothing: 1.0 # gaussian sigma (voxels) before marching cubes; 0 disables
surface_level: 0.5 # isosurface level for marching cubes
downsample_for_surface: 1 # integer >1 to speed up marching cubes (e.g., 2,3); 1 = no downsample

